export enum ID {
  GENERAL = "general",
  SCOPE_OF_SERVICE_AND_THE_LICENSE = "scope-of-service-and-the-license",
  REGISTRATION = "registration",
  USER_OBLIGATIONS_AND_RESTRICTIONS = "user-obligations-and-restrictions",
  INTELLECTUAL_PROPERTY = "intellectual-property",
  REPRESENTATIONS_AND_WARRANTIES = "representations-and-warranties",
  USER_CONTENT = "user-content",
  APPLICATION_CONTENT = "application-content",
  GROUP_ADMINS = "group-admins",
  PRIVACY = "privacy",
  DISCLAIMER = "disclaimer",
  LIMITATION_OF_LIABILITY = "limitation-of-liability",
  INDEMNIFICATION = "indemnification",
  THIRD_PARTY_SERVICES_OR_CONTENT = "third-party-services-or-content",
  LINKS = "links",
  SUBSCRIPTION_AND_PAYMENTS = "subscription-and-payments",
  REFUND_POLICY = "refund-policy",
  MISCELLANEOUS = "miscellaneous",
}
