import { Clause, Heading, Section, TLDR } from "@/app/tos/components/ui/term";
import { ID } from "@/app/tos/constants/id";

export default function Disclaimer(): React.ReactNode {
  return (
    <Section id={ID.DISCLAIMER}>
      <Heading>11. Disclaimer</Heading>
      <TLDR>
        Our app is a take-it-as-you-find-it deal, with no promises of perfection or guarantees, meaning any bugs,
        inaccuracies, or issues fall on your lap, not ours, so use it wisely!
      </TLDR>
      <Clause>
        THE APPLICATION is PROVIDED ON AN “AS IS,” “AS-AVAILABLE,” AND “WITH ALL FAULTS” BASIS, WITHOUT WARRANTY OF ANY
        KIND. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY EXPLICITLY DISCLAIMS ALL WARRANTIES OF ANY
        KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
        PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE ENTIRE RISK ARISING OUT OF YOUR USE OF OR ACCESS TO THE
        APPLICATION REMAINS WITH YOU. THE COMPANY DOES NOT REPRESENT OR WARRANT THAT: (I) THE APPLICATION SHALL BE
        ERROR-FREE OR THAT ANY ERRORS WILL BE CORRECTED; (II) THE APPLICATION SHALL NOT CONTAIN ANY BUGS, VIRUSES,
        TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE APPLICATION BY ANY THIRD PARTY; (III) THE
        OPERATION OF THE APPLICATION WILL BE UNINTERRUPTED OR THAT IT WILL BE ABLE TO BE USED AT ANY TIME, NOR DOES THE
        COMPANY WARRANT ANY CONNECTION TO OR TRANSMISSION FROM THE INTERNET; (IV) THE APPLICATION CONTENT IS IN ANY WAY
        ACCURATE, CURRENT OR COMPLETE; (V) THE APPLICATION WILL MEET YOUR REQUIREMENTS. COMPANY SHALL NOT BE RESPONSIBLE
        FOR UNAUTHORIZED ACCESS TO OR ALTERATION TO THE APPLICATION OR THE ACCOUNT AND WILL NOT BE LIABLE FOR ANY
        DAMAGES OR LOSS INCURRED TO YOU, OR ANY OTHER THIRD PARTY, AS A RESULT, OR IN CONNECTION WITH THE USE OF OR
        RELIANCE ON THE APPLICATION OR ANY INFORMATION DERIVED THROUGH THE APPLICATION. IN ADDITION, THE COMPANY SHALL
        NOT BE RESPONSIBLE OR LIABLE FOR UNAUTHORIZED ACCESS TO YOUR SYSTEMS OR FOR YOUR USE OF THE APPLICATION.
      </Clause>
    </Section>
  );
}
